
export const OPEN_DRAWER = 'OPEN_DRAWER';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';

//
export const SURVEY_LIST_REQUEST = "SURVEY_LIST_REQUEST";
export const SURVEY_LIST_SUCCESS = "SURVEY_LIST_SUCCESS";
export const SHOW_NEXT_QUESTION = "SHOW_NEXT_QUESTION";
export const SHOW_PREVIOUS_QUESTION = "SHOW_PREVIOUS_QUESTION";
export const SET_SELECTED_SURVEY = "SET_SELECTED_SURVEY";
export const INITIALIZE_NAVIGATION_STATE = "INITIALIZE_NAVIGATION_STATE";
export const UPDATE_CHOICES = "UPDATE_CHOICES";
export const CREATE_CHOICES = "CREATE_CHOICES";
export const CREATE_CHOICES_SUCCESS = "CREATE_CHOICES_SUCCESS";

export const EXECUTE_CREATE_CHOICES = "EXECUTE_CREATE_CHOICES";
export const UPDATE_SURVEY_FLAGS = "UPDATE_SURVEY_FLAGS";
export const COMPLETED_SURVEY_LIST_REQUEST = "COMPLETED_SURVEY_LIST_REQUEST";
export const COMPLETED_SURVEY_LIST_SUCCESS = "COMPLETED_SURVEY_LIST_SUCCESS";
export const COMPLETED_SURVEY_LAST5MIN_LIST_REQUEST = "COMPLETED_SURVEY_LAST5MIN_LIST_REQUEST";
export const COMPLETED_SURVEY_LAST5MIN_LIST_SUCCESS = "COMPLETED_SURVEY_LAST5MIN_LIST_SUCCESS";
export const SET_SELECTED_COMPLETED_SURVEY = "SET_SELECTED_COMPLETED_SURVEY";
export const FILTER_SURVEY_LIST = "FILTER_SURVEY_LIST";
export const UPDATE_SAVED_CHOICES = "UPDATE_SAVED_CHOICES";
export const UPDATE_CHOICE_OWNER_NAME = "UPDATE_CHOICE_OWNER_NAME";
export const SET_SELECTED_DISTRICT_OPTIONS = "SET_SELECTED_DISTRICT_OPTIONS";
export const PROCESS_NEXT_CREATE_CHOICE = "PROCESS_NEXT_CREATE_CHOICE";
export const START_SURVEY = "START_SURVEY";

// district

export const GET_DISTRICT_LIST_REQUEST = "GET_DISTRICT_LIST_REQUEST";
export const GET_DISTRICT_LIST_SUCCESS = "GET_DISTRICT_LIST_SUCCESS";
export const GET_NEIGHBOURHOOD_OF_DISTRICT_REQUEST = "GET_NEIGHBOURHOOD_OF_DISTRICT_REQUEST";
export const GET_NEIGHBOURHOOD_OF_DISTRICT_SUCCESS = "GET_NEIGHBOURHOOD_OF_DISTRICT_SUCCESS";

// auth
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const APP_INITIALIZED = "APP_INITIALIZED";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";